name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Check secrets
        run: |
          echo "KEY=${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "SECRET=${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "REGION=${{ secrets.AWS_REGION != '' }}"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check secrets
        run: |
          echo "KEY=${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "SECRET=${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "REGION=${{ secrets.AWS_REGION != '' }}"

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build Image
        run: |
          docker build -t my-node-app .

      - name: Tag Image
        run: |
          docker tag my-node-app:latest \
          ${{ steps.login-ecr.outputs.registry }}/my-node-app:latest

      - name: Push Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/my-node-app:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/my-node-app

            aws ecr get-login-password \
            --region us-east-1 \
            | docker login \
            --username AWS \
            --password-stdin \
            841926064682.dkr.ecr.us-east-1.amazonaws.com

            docker compose pull

            docker compose up -d
